### PR TITLE
Update Genesis with intial accounts, gentxs, start time

### PR DESCRIPTION
**Pull request by JakeHartnell**

### CODE REVIEW

**Comment by the-frey** [comment]
At a glance, it looks like the numbers line up based on the resolution to the issue we saw before. Let's try it.

**Comment by JakeHartnell** [comment]
Ok, getting one error:
```
panic: signature verification failed; please verify account number (0) and chain-id (lucina): unauthorized
```

**Comment by faddat** [comment]
```
Error: error reading GenesisDoc at /home/faddat/.juno/config/genesis.json: invalid character 'A' after top-level value
Usage:
```

**Comment by JakeHartnell** [comment]
> ```
> Error: error reading GenesisDoc at /home/faddat/.juno/config/genesis.json: invalid character 'A' after top-level value
> Usage:
> ```

Really?

Seems fine to me?

```
➜  config junod validate-genesis genesis.json

File at genesis.json is a valid genesis file
```

**Review by dimiandre — APPROVED** [review]
Lgtm!

**Review by Highlander-maker — COMMENTED** [review]
looks like i made it

**Pull request merged**
